backend:
  - any: ['./**/*.js', 'src/server.js']
    all: ['!src/**/*.js']

documentation:
  - ./**/*.md

test:
  - ./**/*.spec.js

frontend:
- any: ['src/**/*.js', 'src/**/*.svelte']
  all: ['!src/server.js']
