backend:
  - any: ['**/!(*.client).js', '**/*.json']
    all: ['!**/src/**/*.js']

documentation:
  - all: ['**/*.md']

test:
  - all: ['**/*.spec.js']

frontend:
  - any: ['**/!(*.server).js', '**/src/**/*.svelte']
    all: ['!**/src/**/*.server.js']
